[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "shooter"
description = "Boson camera control"
dynamic = ["version", "dependencies"]


[tool.setuptools.packages.find]
where = [
    "src",
    "external/boson-sdk/src"
]


[tool.setuptools.package-data]
shooter = ["conf/*.json"]


[tool.setuptools.dynamic]
version = {attr = "shooter.version.__version__"}
dependencies = {file = [
    "requirements/runtime.txt",
    "external/boson-sdk/requirements/runtime.txt"
]}


[project.scripts]
shooter = "shooter.shooter:main"
